# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bd70e57a55cbabae06edb298374f424d7898a628ec4998746b4f68a2ebce27a43f505a410e5d473a08e75f79c1299bfc1e7ca8de501ae4171fed9e905c24395

test:
  secret_key_base: dda0340498e88603073a6ddd06647214e50c53f5cef56341c9f956624a05bd4f9330fdfc9eaa0c4f3dce188b6d9afaf01deec313773cdb7577dd8f11195f4235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
